---
driver_plugin: vagrant
provider: chef_zero

platforms:
- name: centos-6.4_chef-11.4.4
  driver_config: 
    box: opscode-centos-6.4_chef-11.4.4
    box_url:  https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
- name: ubuntu-12.04_chef-11.4.4
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box

suites:
- name: default
  run_list:
    - recipe[ktc-etcd]
    - recipe[ktc-openstack-ha]
    - recipe[ktc-iptables::mysql]
  attributes:
    etcd:
      args: '-c 127.0.0.1:4001 -s 127.0.0.1:7001 -f'
      servers:
        - 127.0.0.1
    vips:
      mysql:
        - ip: 127.0.0.1
        - port: 3306
      identity-api:
        - ip: 127.0.0.1
        - port: 5000
